### ISSUE TITLE
On derive macros

### ISSUE THREAD

**Issue by LucaCappelletti94** [devashishdxt/deli#2]
Hi, switching here from the [`idb`](https://github.com/devashishdxt/idb) crate. You said you _attempted to implement_ the derives, which assumes means you encountered some problems. May I ask what are these?

**Comment by devashishdxt** [comment]
Hi. I didn’t encounter any problems. I just lost motivation as there aren’t any users of this crate. 😅

You can try updating this crate with latest version of `idb`. This crate currently has few limitations.

- Does not allow composite primary keys.
- The API is not very clean.

There may be other things missing which I may have forgotten. You can take a look at the code. I’d appreciate if you can make any contributions.

**Comment by LucaCappelletti94** [comment]
Ok! I will most likely need composite primary keys, would it be okay if I opened another issue to discuss that feature before I try to bake it in?

**Comment by devashishdxt** [comment]
If we’re able to have a clean API which supports all the different things in IndexedDB, we can merge this in `idb` under `derive` feature.

**Comment by devashishdxt** [comment]
> Ok! I will most likely need composite primary keys, would it be okay if I opened another issue to discuss that feature before I try to bake it in?

You’re most welcome.
